### ISSUE TITLE
csv not generating

### ISSUE THREAD

**Issue by santhosh244** [aws-samples/amazon-textract-serverless-large-scale-document-processing#13]
couple of requirements,

Its not generating KeyValues csv as part of the output
Also in a 2 or 3 page document conversion, it generates page-1 and page-2. but when we do from console, we get a single zip with single page document.

**Comment by darwaishx** [comment]
You can update file below to change the output csv behavior.
https://github.com/aws-samples/amazon-textract-serverless-large-scale-document-processing/blob/master/src/og.py
