### ISSUE TITLE
Node.js mentioned in README while code is written in python

### ISSUE THREAD

**Issue by AarushJ** [aws-samples/amazon-textract-serverless-large-scale-document-processing#16]
In the Prerequisites section of README, node.js has been written as a prequisitie, but entire codebase uses python. I think this is a mistype in the README Prerequisites section.

**Comment by darwaishx** [comment]
Project is deployed using AWS CDK and deployment code is written in Typescript. You need node.js for CDK project (not for the Lambda code itself).
