### ISSUE TITLE
If SQS keeps running even no new file send to bucket

### ISSUE THREAD

**Issue by michaelcwang2** [aws-samples/amazon-textract-serverless-large-scale-document-processing#5]
It seems SQS keeps counting even no new file upload to bucket, it would go over the free tier level in one month as my experience. So trying to see if it can be stopped or needs to be fixed.

**Comment by darwaishx** [comment]
You can lower the rate of scheduled Lambda invocation. 
https://github.com/aws-samples/amazon-textract-serverless-large-scale-document-processing/blob/master/textract-pipeline/lib/textract-pipeline-stack.ts#L216

Other option would be to change scheduled Lambda to how Lambda in sync path behaves. Downside of that change is that when you have scheduled maximum number of job, that Lambda will continue to trigger if there are more items in the queue. For many production workloads default arch is recommended way to handle incoming documents, but depending on the traffic pattern you can make that change.
