### ISSUE TITLE
TextractPipelineStack not compatible with CDK 1.15

### ISSUE THREAD

**Issue by chillitom** [aws-samples/amazon-textract-serverless-large-scale-document-processing#7]
This solution requires using an outdated version of CDK, if trying to install using the latest CDK tools you get an error message saying that CDK libs must be of version 1.10 or greater. 

`The CDK CLI you are using requires your app to use CDK modules with version >= 1.10.0`

 Updating the dependencies of the project creates 43 build errors in the Typescript compile stage.

**Comment by stevebez** [comment]
Can anyone provide a solution to this? Do I need to downgrade the CDK to get the deployment to work?

**Comment by darwaishx** [comment]
Solution has been updated with current version of CDK. Earlier as listed in the steps it worked with cdk version 0.28.
