### ISSUE TITLE
Node 8.10 not supported anymore

### ISSUE THREAD

**Issue by keherri** [aws-samples/amazon-textract-serverless-large-scale-document-processing#9]
```The runtime parameter of nodejs8.10 is no longer supported for creating or updating AWS Lambda functions. We recommend you use the new runtime (nodejs12.x) while creating or updating functions.```

**Nodejs version needs to be changed to 12.12.6**

### package-lock.json 
```
"@types/node": {
      "version": "12.12.6",
      "resolved": "https://registry.npmjs.org/@types/node/-/node-12.12.6.tgz",
      "integrity": "sha512-FjsYUPzEJdGXjwKqSpE0/9QEh6kzhTAeObA54rn6j3rR4C/mzpI9L0KNfoeASSPMMdxIsoJuCLDWcM/rVjIsSA==",
      "dev": true
    },
```

### package.json
```
"@types/node": "12.12.6",
```

### Run in textract-pipeline
```
grep -ilr 'nodejs8.10' * | xargs -I@ sed -i '' 's/nodejs8.10/nodejs12.x/g' @
```

**Comment by keherri** [comment]
### package-lock.json 
```
"@types/node": {
      "version": "12.12.6",
      "resolved": "https://registry.npmjs.org/@types/node/-/node-12.12.6.tgz",
      "integrity": "sha512-FjsYUPzEJdGXjwKqSpE0/9QEh6kzhTAeObA54rn6j3rR4C/mzpI9L0KNfoeASSPMMdxIsoJuCLDWcM/rVjIsSA==",
      "dev": true
    },
```

## package.json
```
"@types/node": "12.12.6",
```

## Run in textract-pipeline
```
grep -ilr 'nodejs12.12' * | xargs -I@ sed -i '' 's/nodejs8.10/nodejs12.x/g' @
```

**Comment by Sharonfun101** [comment]
We are still seeing this issue after running the above workaround and verify that the package.json no longer have node 8.10.  Any insights why?

**Comment by darwaishx** [comment]
Solution has been updated with current version of CDK to fix this issue.
